baseURL = "https://antonija.me/"
language = "en"
theme = "antonija"
title = "Antonija Kasum | Frontend Developer"
description = "Frontend developer based in Helsinki. I enjoy using Javascript to turn ideas into code."
images = ["/img/social-image.jpeg"]
publishDir = "docs"

[params]
  description = "Frontend developer based in Helsinki. I enjoy using Javascript to turn ideas into code."
  images = ["/img/social-image.jpeg"]
  title = "Antonija Kasum | Frontend Developer"