baseURL = "https://antonijakasum.com/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "antonija"
title = "Antonija Kasum · Landing Page"
publishDir = "docs"


[blackfriday]
extensions = ["hardLineBreak"]

[permalinks]
fixed = ":title/"
posts = "posts/:slug/"

[params]
author = "Antonija Kasum"
description = "Portfolio"

	[params.contact]
    email = "hello@antonijakasum.com"
    github = "antonijak"